name: Front-end CD

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name:
      run: npm ci
    - name: Build Shared Library
      run: npm run build who-ems
    - name: Build Back-office
      run: npm run build:ci
    - name: Build Front-office
      run: npm run build:ci front-office
    # - name: Test
    #   run: npm run test:ci
    - name: Archive build Back-office
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: deploy_dist_back_office
        path: dist/back-office
    - name: Archive build Front-office
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: deploy_dist_front_office
        path: dist/front-office
    # - name: Archive code coverage result
    #   if: success()
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: deploy_coverage
    #     path: coverage


  deploy_back_office:
    name: Deploy Back-office
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: deploy_dist_back_office
        path: dist/back-office
    - name: Setup SSH Keys and known_hosts
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy
      run: ./CI/deploy-back-office.sh
      env:
        SSH_PASS: ${{ secrets.SSH_PASS }}


  deploy_front_office:
    name: Deploy Back-office
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: deploy_dist_front_office
        path: dist/front-office
    - name: Setup SSH Keys and known_hosts
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy
      run: ./CI/deploy-front-office.sh
      env:
        SSH_PASS: ${{ secrets.SSH_PASS }}
